export enum Permissions {
    QuanTriDanhMucDuLieu = 'QuanTriDanhMucDuLieu',
    QuanTriDanhMucThuTucHanhChinh = 'QuanTriDanhMucThuTucHanhChinh',
    ThuThapDuLieuHeThong = 'ThuThapDuLieuHeThong',
    DuyetDuLieuHeThong = 'DuyetDuLieuHeThong',
    ChiaSeDuLieuHeThong = 'ChiaSeDuLieuHeThong',
    KhaiThacDuLieuHeThong = 'KhaiThacDuLieuHeThong',
    ThuThapDuLieuDonVi = 'ThuThapDuLieuDonVi',
    DuyetDuLieuDonVi = 'DuyetDuLieuDonVi',
    ChiaSeDuLieuDonVi = 'ChiaSeDuLieuDonVi',
    KhaiThacDuLieuDonVi = 'KhaiThacDuLieuDonVi',
    QuanTriDanhMucTrenCongCanBo = 'QuanTriDanhMucTrenCongCanBo',
    TraCuuDuLieuTrenCongCanBo = 'TraCuuDuLieuTrenCongCanBo',
    QuanTriDanhMucTrenCongDuLieuMo = 'QuanTriDanhMucTrenCongDuLieuMo',
    QuanTriTaiKhoanCongDanTrenCongDuLieuMo = 'QuanTriTaiKhoanCongDanTrenCongDuLieuMo',
    QuanTriDuLieuCongDan = 'QuanTriDuLieuCongDan',
}
